### ISSUE TITLE
大佬请教下，我搭的项目i18已经成功注入了，但是antd样式还是默认英文

### ISSUE THREAD

**Issue by sewth** [yyong008/remix-antd-admin-electron#1]
```typescript
import { useTranslation } from 'react-i18next';
let { t } = useTranslation();
header {t('greeting')}
``` 
我在页面上试了下，greeting能正常显示你好。不过antd的组件还是默认英文。
<img width="305" alt="image" src="https://github.com/yyong008/remix-antd-admin-electron/assets/21299462/5f1f2dee-5096-4e27-b597-eeb907948c53">
<img width="305" alt="image" src="https://github.com/yyong008/remix-antd-admin-electron/assets/21299462/dc828a3b-abeb-4ec0-8c22-f0fb5b818901">

项目git地址是： https://github.com/sewth/remix-express-antd

大佬帮看下，是哪里还是有问题吗。

项目技术是
remix 2.0.1
express 4.18.2
antd: 5.9.4

**Comment by yyong008** [comment]
> 我在页面上试了下，greeting能正常显示你好。不过antd的组件还是默认英文。

是 No data 还是英文，还是别的？ 前者这应该是 antd 组件的默认行为吧，处理方式是覆盖默认行为。

**Comment by sewth** [comment]
> > 我在页面上试了下，greeting能正常显示你好。不过antd的组件还是默认英文。
> 
> 是 No data 还是英文，还是别的？ 前者这应该是 antd 组件的默认行为吧，处理方式是覆盖默认行为。

是的 No data这个不符合预期，我是改成了zh_CN了，但是antd里面默认还是英文，覆盖默认行为需要怎么配置吗

**Comment by yyong008** [comment]
> 覆盖默认行为需要怎么配置吗

antd 与 i18n 是分开的

**Comment by sewth** [comment]
> > 覆盖默认行为需要怎么配置吗
> 
> antd 与 i18n 是分开的

antd是也要配置ConfigProvider吗 不过我试了在entry.client.tsx entry.server.tsx root.tsx配置都不起作用

**Comment by yyong008** [comment]
> 配置都不起作用

`<Table locale={{ emptyText: '没有数据'}}/>`

**Comment by sewth** [comment]
> locale

哦哦 明白了 每个组件都要单独设置，谢谢大佬
